<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>CITYLOCATE</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
              crossorigin="" />
        <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
                crossorigin=""></script>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
              integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
              crossorigin=""/>
        <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
                integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
                crossorigin=""></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <script type="text/javascript">
            // On initialise la latitude et la longitude de Belfort (centre de la carte)
            var lat = 47.6333;
            var lon = 6.8667;
            var macarte = null;
            // Fonction d'initialisation de la carte

        </script>

        <style type="text/css">
            #map{ /* la carte DOIT avoir une hauteur sinon elle n'apparaît pas */
                height:400px;
            }
            #jeu{
                margin: 0 10%;
            }
            #titre{
                text-align: center;
            }
            #reload{
                margin-left: 45%;
                width: 200px;
            }
        </style>

    </head>
    <body>
    <div id="titre">
        <h1>City Locate</h1>
    </div>
    <div id="formulaire">
        <h2>Se connecter :</h2>
        <fieldset id="logi" >
            Identifiant <br>
            <input id="identifiant" class="form-control" type="text">
            <br>
            Mot de passe <br>
            <input id="mdp"  class="form-control" type="password" >
            <br>
            <button id="login" type="submit" class="btn btn-primary">Jouer</button>
        </fieldset><br>
        <h2>S'enregistrer :</h2>
        <fieldset id="regi" >
            Identifiant <br>
            <input id="identifiantR" class="form-control" type="text">
            <p id="erreur_id" style="display: none">Identifiant trop petit</p>
            <br>
            Mot de passe <br>
            <input id="mdpR" class="form-control" type="password">
            <p id="erreur_mdp" style="display: none;">Veuillez saisir un mdp de 8caractere minimum</p>
            <br>
            Mot de passe (confirmation) <br>
            <input id="mdpRC" class="form-control" type="password">
            <p id="erreur_mdp" style="display: none;">Veuillez saisir un mdp de 8caractere minimum</p>
            <br>
            <button id="register" type="submit" class="btn btn-primary">Enregistrer</button>
        </fieldset>
    </div>
    <div id="jeu">
        Score :
        <div id="score">0</div>
        <div id="map"></div>
        <img id="image" src="">
    </div>

    <div id="fin">
        <div id="scoreFin" style="text-align: center"></div>
        <button id="reload" class="btn btn-primary">NOUVELLE PARTIE</button>
    </div>

    </body>


<script type="text/javascript">
    function convertRad(a) {
        return (Math.PI * a) / 180;
    }
    function Distance(lat_a_degre, lon_a_degre, lat_b_degre, lon_b_degre) {
        R = 6378000;
        lat_a = convertRad(lat_a_degre);
        lon_a = convertRad(lon_a_degre);
        lat_b = convertRad(lat_b_degre);
        lon_b = convertRad(lon_b_degre);
        d = R * (Math.PI / 2 - Math.asin(Math.sin(lat_b) * Math.sin(lat_a) + Math.cos(lon_b - lon_a) * Math.cos(lat_b) * Math.cos(lat_a)));
        return d;
    }

    $("#jeu").hide();
    $("#fin").hide();
    var token = '';
    var idPartie;


    $.get("/getToken",function (data) {
        token = data["token"];
        //console.log(token);
    });

    $("#login").click(function () {
        var identifiant = $("#identifiant").val();
        var mdp = $("#mdp").val();
        var verif;
        var score = 0;

        verif = $.post("/login",{'identifiant':identifiant,'mdp':mdp,'token':token},function (data) {
            verif = data['verif'];
            var verif2 = data['verif2'];
            //console.log(verif2);
            if(verif === 'OK'){
                $("#formulaire").hide();
                $("#jeu").show();
                macarte = L.map('map').setView([lat, lon], 13);
                L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
                }).addTo(macarte);
                $.post("/play/games",{'pseudo':identifiant},function (data) {
                    idPartie = data['0']['id'];
                    //console.log(idPartie);
                        $.get("/play/{id}/games",{'id':idPartie},function (data) {
                            //console.log(data);
                            var i = 0;
                            document.getElementById('image').src=data[i][2];
                            macarte.on('click', function(e) {
                                //console.log(e.latlng);
                                var marker = L.marker(e.latlng).addTo(macarte);

                                var lat = e.latlng['lat'];
                                var lng = e.latlng['lng'];

                                var distance = Distance(lat,lng,data[i][3],data[i][4]);

                                if(distance<100){
                                    score = score + 5;
                                }else if(distance<200){
                                    score = score + 3;
                                }else if(distance<300){
                                    score = score + 1;
                                }
                                document.getElementById("score").innerHTML = score;

                                if(i===9){
                                    //appelle fonction de fin de partie.
                                    //console.log(score);
                                    $.post("/play/games/fin",{'id':idPartie,'score':score},function (d) {
                                        //console.log(d);
                                        //console.log(d['id']);
                                        document.getElementById("scoreFin").innerHTML = "Vous avez terminé la partie avec "+score+" points";
                                        $("#fin").show();
                                        $("#jeu").hide();
                                        $("#reload").click(function () {
                                            window.location.reload(true);
                                        });
                                    });
                                    return;
                                }
                                i = i + 1;
                                document.getElementById('image').src=data[i][2];
                            });
                        });
                });

            }

        });
   });
    $("#register").click(function () {
        var identifiant = $("#identifiantR").val();
        var mdp = $("#mdpR").val();
        var mdrC = $("#mdpRC").val();
        if(identifiant.length<=1){
            $("#erreur_id").css("display","block");
            return;
        }else{
            $("#erreur_id").css("display","none");
        }
        if(mdp.length<=7){
            $("#erreur_mdp").css("display","block");
            return;
        }else{
            $("#erreur_mdp").css("display","none");
        }
        if(mdp !== mdrC){
            return;
        }
        console.log(mdp);
        $.post("/register",{'identifiant':identifiant,'mdp':mdp,'token':token}, function (data) {
            var id = data["id"];
            console.log(id);
        });
    });
</script>
</html>
